name: "Update Go Workspace"
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  issue_comment:
    types: [created]
permissions:
  contents: write
jobs:
  handle-pull-request-event:
    runs-on: "ubuntu-latest"
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/update-go-workspace') }}
    continue-on-error: true
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set go version
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: Update workspace
      run: make update-workspace

    - name: Commit and push workspace changes
      run: |
        if ! git diff --exit-code --quiet; then
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local --add --bool push.autoSetupRemote true
          echo "Committing and pushing workspace changes"
          git commit -a -m "update workspace"
          git push
        fi
